require "dotenv"
require "httparty"
require "json"
require 'open3'
require 'colorize'
require_relative 'lib/app'

Dotenv.load
api_key = ENV["API_KEY"]

system("clear")
puts("English or Italian? (it/en)")
user_language = gets.chomp.downcase

until user_language == "it" || user_language == "en"
  puts("try again/riprova")
  user_language = gets.chomp.downcase
end

user_language = user_language.to_sym

system("clear")

cli_messages = {
  en: {
    welcome: "Welcome!",
    important_info: "VERY IMPORTANT!!\nCopy the path of the folder your 'video_to_subtitle.mp4' (rename it with that exact name) is in, only THEN press return.",
    overwrite_warning: "If the program stops and asks you to type [y/N], type y, this will overwrite any previous audio generated by this program.\nPress return to continue <-",
    success: "Lessgooo, subtitles created!"
  },
  it: {
    welcome: "Benvenuto!",
    important_info: "MOLTO IMPORTANTE!!\nCopia il percorso in cui il tuo video chiamato 'video_to_subtitle.mp4' (rinominalo con quel nome esatto) si trova e DOPO premi invio.",
    overwrite_warning: "Se il programma si ferma e ti chiede di inserire [y/N], premi y, questo sovrascriverà eventuali audio già creati in precedenza da questo programma.\nPremi invio per continuare <-",
    success: "Dajeeee, sottotitoli creati!"
  }
}

puts(cli_messages[user_language][:welcome].colorize(:green))
puts(cli_messages[user_language][:important_info].colorize(:red))
gets
puts(cli_messages[user_language][:overwrite_warning])
gets

# get copied path from clipboard and set it as operational path
full_path, _status = Open3.capture2("pbpaste")
full_path.strip!
home_directory = Dir.home
relative_path = full_path.sub(/^#{home_directory}/, '')
operational_directory = File.join(home_directory, relative_path)

app = App.new(api_key, operational_directory)
app.generate_subtitles

puts(cli_messages[user_language][:success].colorize(:green))





